# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import models, migrations



class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20161218_1614'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS hstore"),
        migrations.AddField(
            model_name='product',
            name='features',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]

