# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20170106_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateogry',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Cateogry'),
        ),
    ]
