# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_parent_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
