# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20170122_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateogry',
            old_name='parent_category',
            new_name='parent_cateogry',
        ),
    ]
