# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20170125_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifiedcategory',
            options={'ordering': ['name'], 'verbose_name': 'modified category', 'verbose_name_plural': 'modified categories'},
        ),
        migrations.AlterField(
            model_name='modifiedproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='modifiedproducts/%Y/%m/%d'),
        ),
    ]
