# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170128_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'images related with products', 'verbose_name_plural': 'Product Images'},
        ),
    ]
