# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20170128_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifiedproduct',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created']},
        ),
    ]
