# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20170201_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiedproduct',
            name='image',
        ),
    ]
