# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_modifiedproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
