# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_modifiedcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedproduct',
            name='option_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
