# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_modifiedproduct_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedproduct',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
