# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_modifiedproduct_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedproduct',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
    ]
