# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20170223_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedproduct',
            name='optional_visible_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
