# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincodes', '0003_auto_20170301_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='officeName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='taluk',
            field=models.CharField(max_length=50),
        ),
    ]
