# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pincodes', '0001_initial'),
        ('shop', '0035_auto_20170223_0611'),
        ('orders', '0004_auto_20170226_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.ModifiedProduct')),
                ('available_pincode', models.ManyToManyField(to='pincodes.Pincode')),
            ],
        ),
    ]
