# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='availability_group',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Selective Places')], default=0),
        ),
    ]
