# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='jail',
            new_name='controller_jail',
        ),
        migrations.AddField(
            model_name='maps',
            name='name',
            field=models.CharField(default='asadas', max_length=100),
            preserve_default=False,
        ),
    ]
